name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies and Test
      run: |
        yarn
        yarn test

    - name: Deploy
      run: |
        git config --global user.name $user_name
        git config --global user.email $user_email
        echo https://${github_token}@github.com/${repository}
        git remote set-url origin https://${github_token}@github.com/${repository}
        yarn deploy
      env:
        user_name: 'olololoe110399'
        user_email: 'duynn100198@gmail.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
